import { createElement } from 'lwc';
import SC_SearchDocumnetLWC from 'c/sC_SearchDocumnetLWC';

describe('c-s-c-search-documnet-lwc', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-s-c-search-documnet-lwc', {
            is: SC_SearchDocumnetLWC
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});